services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=localhost
      - DATABASE_URL=ecto://postgres:postgres@db/cognitus_prod
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cognitus_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: