services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - MIX_ENV=prod
    command: sh -c "mix local.hex --force && mix deps.get --only prod && mix deps.compile && mix phx.server"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cognitus_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: